mysite/urls.py
from django.urls import include, path

urlpatterns = [
    path('', include('phra.urls')),
]

phra/urls.py
from django.urls import path

from . import views

app_name = "phra"
urlpatterns = [
    # path("", views.index, name="index"),
    path("", views.patient_list, name="phra"),
    path("patients/add", views.patient_form, name="patient_form"),
    path("patients/add_submit", views.patient_add_submit, name="patient_add_submit"),
    path("records/<int:patient_id>", views.records_list, name="records"),
    path("records/<int:patient_id>/add", views.records_form, name="records_add"),
    path("records/<int:patient_id>/add_submit", views.records_add_submit, name="records_add_submit"),
    path("records/<int:record_id>/detail", views.record_detail, name="records_record_detail"),
]

phra/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class CdPatient(models.Model):
    patient_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=30, blank=True, null=True, db_comment='first name or last name for ppl from other country.')
    last_name = models.CharField(max_length=30, blank=True, null=True, db_comment='first name or last name for ppl from other country.')
    patient_system_id = models.CharField(unique=True, max_length=100, db_comment='e.g. SAP ID')

    class Meta:
        managed = False
        db_table = 'cd_patient'


class LabRecord(models.Model):
    record_id = models.BigAutoField(primary_key=True)
    patient = models.ForeignKey(CdPatient, on_delete=models.CASCADE)
    lab_record_id = models.CharField(unique=True, max_length=100)
    appointment_note = models.TextField(blank=True, null=True)
    result_dt = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'lab_record'


class LabResults(models.Model):
    result_id = models.BigAutoField(primary_key=True)
    spec_amount = models.CharField(max_length=100, blank=True, null=True)
    spec_description = models.CharField(max_length=50, blank=True, null=True)
    lab_record = models.ForeignKey(LabRecord, on_delete=models.CASCADE)
    type = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'lab_results'

phra/views.py
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import CdPatient, LabRecord, LabResults


def index(request):
    return HttpResponse("")


def patient_list(request):
    patient_data = CdPatient.objects.order_by('last_name')
    context = {
        "patient_data": patient_data
    }
    print(patient_data)
    return render(request, "phra/patient-list.html", context)


def patient_form(request):
    return render(request, "phra/patient-form.html")


def patient_add_submit(request):
    first_name = request.POST['firstName']
    last_name = request.POST['lastName']
    patient_id = request.POST['patientId']
    try:
        cd_patient = CdPatient(patient_system_id=patient_id, first_name=first_name, last_name=last_name)
        cd_patient.save()
    except IntegrityError:
        context = {
            'error_message' : "Patient Serial Number is already exists",
            'patient_id': patient_id
        }
        return render(request, "phra/patient-form.html", context)
    return HttpResponse("Patient Added. Click <a href='/'>here</a> to view.")


def records_list(request, patient_id):
    patient = get_object_or_404(CdPatient, pk=patient_id)
    records = LabRecord.objects.filter(patient_id=patient_id)
    context = {
        "records": records,
        "patient": patient
    }
    return render(request, "phra/record-list.html", context)


def records_form(request, patient_id):
    context = {
        'patient_id': patient_id
    }
    return render(request, "phra/record-form.html", context)


def records_add_submit(request, patient_id):
    lab_result = request.POST['labResult']
    lab_record_id = request.POST['labRecordId']
    prescription = request.POST['prescription']
    appointment_note = request.POST['appointmentNote']
    try:
        lab_record = LabRecord(patient_id=patient_id, lab_record_id=lab_record_id, appointment_note=appointment_note)
        lab_record.save()

        record_id = lab_record.record_id
        for result in lab_result.split(','):
            save_lab_result(lab_record, result, 1)
        for result in prescription.split(','):
            save_lab_result(lab_record, result, 2)
    except:
        context = {
            'error_message' : 'Unable to save record',
            'patient_id': patient_id
        }
        return render(request, "phra/record-form.html", context)
    return HttpResponse(
        f"Lab Record Added. Click <a href='/records/{patient_id}'>here</a> to view.")

def save_lab_result(lab_record, data, type):
    if "-" in data:
        d = data.split("-")
        lab_result = LabResults(lab_record=lab_record,spec_amount= d[0], spec_description=d[1], type = 1)
        lab_result.save()
    else :
        lab_result = LabResults(lab_record=lab_record,spec_amount= data, spec_description='', type = 2)
        lab_result.save()


def record_detail(request, record_id):
    lab_record = get_object_or_404(LabRecord,pk=record_id)
    patient = get_object_or_404(CdPatient,pk=lab_record.patient.patient_id)
    lab_results = LabResults.objects.filter(lab_record = lab_record)
    context = {
        'lab_record': lab_record,
        'patient': patient,
        'lab_results': filter(lambda result : result.type == 1, lab_results),
        'prescriptions': filter(lambda result : result.type == 2, lab_results)
    }
    return render(request, "phra/record-detail.html", context)

phra/templates/phra/patient-form.html
<a href="/"> back </a>

<form action="{% url 'phra:patient_add_submit' %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>Add New patient</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <label>First Name: </label>
    <input type="text" name="firstName" id="firstName" value="" /> <br />
    <label>Last Name: </label>
    <input type="text" name="lastName" id="lastName" value="" /> <br />
    <label>Patient ID(From Patient System): </label>
    <input type="text" name="patientId" id="patientId" value="" /> <br />
</fieldset>
<input type="submit" value="Add">
</form>

phra/templates/phra/patient-list.html
<h1>Patient List</h1>

{% if patient_data %}
<ul>
    {% for patient in patient_data %}
    <li><a href="/records/{{ patient.patient_id }}">{{ patient.last_name }}, {{ patient.first_name }} -
        {{ patient.patient_system_id }}</a></li>
    {% endfor %}
</ul>
{% endif %}
<hr/>
<p><a href="patients/add">Add New Patient</a></p>

phra/templates/phra/record-detail.html
<a href="/records/{{patient.patient_id}}"> back </a>

<h1>{{ patient.last_name }}, {{ patient.first_name }} - {{ patient.patient_system_id }}'s Lab Record Detail</h1>
<h3>Patient Name: {{ patient.last_name }}, {{ patient.first_name }}</h3>
<h3>Patient Serial Number: {{ patient.patient_system_id }}</h3>

<h3>Lab Result : </h3>
<ul>
    {% for result in lab_results %}
    <li>{{result.spec_amount}} {{result.spec_description}}</li>
    {% endfor %}
</ul>
<h3>Prescription : </h3>
<ul>
    {% for result in prescriptions %}
    <li>{{result.spec_amount}} {{result.spec_description}}</li>
    {% endfor %}
</ul>
<h3>Appointment Note : </h3>
<pre>
    {{lab_record.appointment_note}}
</pre>
<a href="/records/{{patient.patient_id}}"> back </a>

phra/templates/phra/record-form.html
<form action="{% url 'phra:records_add_submit' patient_id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>Add Patient's Record</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <label>Lab Record Serial Number: </label>
    <input type="text" name="labRecordId" id="labRecordId" value="" /> <br />
    <label>Lab Results: </label>
    <input type="text" name="labResult" id="labResult" value="" /> <br /> (hint: Result separate with - and multiple results can be added by comma separation. e.g. 100 - Cholesterol, 1.5MG - Creatine<br />
    <label>Prescription: </label>
    <input type="text" name="prescription" id="prescription" value="" /> <br /> (hint: Result separate with - and multiple results can be added by comma separation. e.g. 1 Tablet/Day - Vitamin-C, 1 Tablet/Day - Vitamin-D3 <br />
    <label>Appointment Note: </label>
    <textarea type="text" name="appointmentNote" id="pappointmentNote" value=""></textarea> <br />
</fieldset>
<input type="submit" value="Add">
</form>

phra/templates/phra/record-list.html
<h1>{{ patient.last_name }}, {{ patient.first_name }} - {{ patient.patient_system_id }}'s Lab Records List</h1>

{% if records %}
    <ul>
    {% for record in records %}
        <li><a href="/records/{{ record.record_id }}/detail">{{ record.lab_record_id }}</a></li>
    {% endfor %}
    </ul>
{% endif %}
<p><a href="/records/{{patient.patient_id}}/add">Add Patient Record</a></p>